/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Generates a unique identifier for a spec with an optional unique label. */
export function uniqueSpecIdentifier(specName: string, uniqueSpecLabel?: string | undefined | null): string
export function genSpecIdentifier(specName: string, uniqueSpecLabel?: string | undefined | null): string
export interface SpecTagInfoParams {
  specName: string
  uniqueSpecLabel?: string
  tag: string
}
export interface UniqueStreamIdentifierParams {
  from?: SpecTagInfoParams
  to?: SpecTagInfoParams
}
export function uniqueStreamIdentifier(p: UniqueStreamIdentifierParams): string
export class SpecTagInfo {
  specName: string
  tag: string
  uniqueSpecLabel?: string
}
export class FromSpecAndTag {
  specName: string
  output: string
  uniqueSpecLabel?: string
}
export class ToSpecAndTag {
  specName: string
  input: string
  hasTransform: boolean
  uniqueSpecLabel?: string
}
