/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum NodeType {
  RootSpec = 0,
  Spec = 1,
  StreamDef = 2,
  Inlet = 3,
  Outlet = 4,
  Alias = 5
}
export function sumAsString(a: number, b: number): string
export function defGraph(rootSpecName: string, inputTags: Array<string>, outputTags: Array<string>): DefGraph
export class DefGraph {
  /** Deserializes a `DefGraph` from a JSON string. */
  static loadFromJson(jsonStr: string): DefGraph
  /** Serializes the `DefGraph` to a JSON string. */
  toJson(): string
  getAllAliasNodeIds(): Array<number>
  getRootSpecNodeId(): number | null
  lookupSpecAndTagByAlias(alias: string, direction: string): SpecTagInfo | null
  lookupRootSpecAlias(specName: string, tag: string, direction: string): string | null
  constructor(rootSpecName: string, inputTags: Array<string>, outputTags: Array<string>)
}
export class SpecTagInfo {
  specName: string
  tag: string
  uniqueSpecLabel?: string
}
export class FromSpecAndTag {
  specName: string
  output: string
  uniqueSpecLabel?: string
}
export class ToSpecAndTag {
  specName: string
  input: string
  hasTransform: boolean
  uniqueSpecLabel?: string
}
