/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Generates a unique identifier for a spec with an optional unique label. */
export function uniqueSpecIdentifier(specName: string, uniqueSpecLabel?: string | undefined | null): string
export function sumAsString(a: number, b: number): string
export class SpecTagInfo {
  specName: string
  tag: string
  uniqueSpecLabel?: string
}
export class FromSpecAndTag {
  specName: string
  output: string
  uniqueSpecLabel?: string
}
export class ToSpecAndTag {
  specName: string
  input: string
  hasTransform: boolean
  uniqueSpecLabel?: string
}
